import_ap_task: true
import_bd_task: true
import_contract_task: true
import_epg_task: true
import_filter_task: true
import_l3out_task: true
import_tenant_task: true
import_vrf_task: true
import_match_rule_task: true
import_set_rule_task: true
import_route_map_task: true

tenant_name_prefix: ''
tenant_name_suffix: ''
tenant_default_description: ''

filter_name_prefix: ''
filter_name_suffix: ''
filter_default_description: ''

entry_name_prefix: ''
entry_name_suffix: ''
entry_default_description: ''
entry_default_ethertype: 'unspecified'
entry_default_ip_protocol: 'unspecified'
entry_default_from_port: 'unspecified'
entry_default_to_port: 'unspecified'

contract_name_prefix: ''
contract_name_suffix: ''
contract_default_description: ''
contract_default_scope: 'context'

subject_name_prefix: ''
subject_name_suffix: ''
subject_default_description: ''
subject_default_action: 'permit'
subject_default_reverse_filter_port: 'yes'
subject_default_log: false
subject_default_policy_compression: false

vrf_name_prefix: ''
vrf_name_suffix: ''
vrf_default_description: ''
vrf_default_enforcement: 'enforced'
vrf_default_preferred_group: 'disabled'

ap_name_prefix: ''
ap_name_suffix: ''
ap_default_description: ''

bd_name_prefix: ''
bd_name_suffix: ''
bd_default_description: ''
bd_default_endpoint_move_detection: ''
bd_default_l2_unknown_unicast_routing_enabled: 'proxy'
bd_default_l2_unknown_unicast_routing_disabled: 'flood'
bd_default_l3_unknown_multicast_routing_enabled: 'opt-flood'
bd_default_l3_unknown_multicast_routing_disabled: 'flood'
bd_default_arp_flood_routing_enabled: false
bd_default_arp_flood_routing_disabled: true

epg_name_prefix: ''
epg_name_suffix: ''
epg_default_description: ''
epg_default_preferred_group_member: 'exclude'
domain_immediacy: 'pre-provision'
domain_deployment: 'immediate'
interface_deployment: 'immediate'

l3out_name_prefix: ''
l3out_name_suffix: ''
l3out_default_description: ''
l3out_default_import_route_control: true
l3out_default_export_route_control: false

ospf_default_area_type: 'regular'
ospf_default_area_cost: '1'

router_default_loopback: false

l3_interface_default_mtu: 'inherit'

external_epg_default_description: ''
external_epg_default_preferred_group_member: 'exclude'

external_subnet_default_agg_export: false
external_subnet_default_agg_inport: false
external_subnet_default_agg_shared: false
external_subnet_default_export_route_ctrl: false
external_subnet_default_external_epg: false
external_subnet_default_shared_route_ctrl: false
external_subnet_default_shared_security_import: false

bgp_peer_default_description: ''
bgp_peer_default_bfd: false
bgp_peer_default_ttl: 1
bgp_peer_default_weight: 0
bgp_peer_default_send_community: false
bgp_peer_default_send_extended_community: false

match_rule_default_description: ''

set_rule_default_description: ''
set_rule_as_path_default_description: ''

route_map_default_description: ''
route_map_context_default_description: ''