---
- name: Process Multicast Route Maps for tenant {{ tenant.name }}
  include_tasks: wrapper_api_call.yml

  vars:
    path: "/api/mo/uni/tn-{{ tenant.name }}.json"
    payload: "{{ lookup('template', 'mcast_route_map.json.j2') }}"
    dn: "/api/mo/uni/tn-{{ tenant.name }}/rtmap-{{ mcast_route_map.name }}"

  loop: "{{ tenant.policies.mcast_route_maps | default([]) }}"
  loop_control:
    loop_var: mcast_route_map
    label: "{{ [ tenant.name, mcast_route_map.name ] | join('/') }}"

  when:
    - mcast_route_map | has_nested_state

  no_log: "{{ no_log_enabled }}"
