---
- name: Process Route Maps for tenant {{ tenant.name }}
  include_tasks: wrapper_api_call.yml

  vars:
    path: "/api/mo/uni/tn-{{ tenant.name }}.json"
    payload: "{{ lookup('template', 'route_map.json.j2') }}"
    dn: "/api/mo/uni/tn-{{ tenant.name }}/prof-{{ route_map.name }}"

  loop: "{{ tenant.policies.route_maps | default([]) }}"
  loop_control:
    loop_var: route_map
    label: "{{ [ tenant.name, route_map.name ] | join('/') }}"

  when:
    - route_map.state is defined

  no_log: true
