---
- set_fact:
    intf_pg_map: >-
      {{
        intf_pg_map | combine({
          ipg_vars.name:
              'vpc' if ipg_vars.type == 'vpc' else
              'port_channel' if ipg_vars.type == 'po' else
              'switch_port'
        })
      }}

  loop: "{{ ( fabric.intf_policy_groups | default( [] )) }}"
  loop_control:
    loop_var: ipg_vars

- name: Print intf_pg_map
  debug:
    var: intf_pg_map
