---
- name: Import Node Registration tasks
  include_tasks: register.yml

- name: Import Node Decommission tasks
  include_tasks: decommission.yml

- name: Import Intf Selector tasks
  include_tasks: intf.yml

# - name: Import leaf tasks
#   include_tasks: leaf.yml
