---
- set_fact:
    async_jobs: []
    aci_cred: &aci_login
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      use_proxy: no
      use_ssl: yes
      validate_certs: no
      annotation: orchestrator:ansible
  no_log: true

- set_fact:
    leaf_to_vpc_domain_map: "{{ leaf_to_vpc_domain_map | combine({ node_vars.id : [ node_vars.id, node_vars.vpc_peer_id ] | join('-') }) }}"
  when:
    - node_vars.vpc_peer_id is defined
    - node_vars.vpc_peer_id not in leaf_to_vpc_domain_map

- set_fact:
    leaf_to_vpc_domain_map: "{{ leaf_to_vpc_domain_map | combine({ node_vars.id : [ node_vars.vpc_peer_id, node_vars.id ] | join('-') }) }}"
  when:
    - node_vars.vpc_peer_id is defined
    - node_vars.vpc_peer_id in leaf_to_vpc_domain_map

- block:
    - cisco.aci.aci_switch_policy_vpc_protection_group:
        <<: *aci_login
        protection_group: leafPair101-vpcGrp
        protection_group_id: "{{ node_vars.id }}"
        switch_1_id: "{{ node_vars.id }}"
        switch_2_id: "{{ node_vars.vpc_peer_id }}"
        state: "{{ node_vars.state }}"
      delegate_to: localhost
      register: job
      async: 600
      poll: 0

    - set_fact:
        async_jobs: "{{ async_jobs + [ job ]}}"

  when:
    - node_vars.vpc_peer_id is defined
    - node_vars.vpc_peer_id not in leaf_to_vpc_domain_map
